server:
  port: 8087

spring:
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
    memory:
      mysql:
        enabled: true
#      sqlite:
#        enabled: true
      redis:
        host: localhost
        port: 6379
  datasource:
#    url: jdbc:sqlite:spring-ai-alibaba-chat-memory-example/src/main/resources/chat-memory.db
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&tinyInt1isBit=false&allowLoadLocalInfile=true&allowLocalInfile=true&allowUrl
    username: root
    password: passwd4mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
